# Generated by Django 5.0.6 on 2024-07-31 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornitore_nome', models.CharField(max_length=128, unique=True)),
                ('fornitore_cod_as', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InserimentoFallito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dati_riga', models.JSONField()),
                ('errore', models.TextField()),
                ('data_tentativo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Magazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazzino_nome', models.CharField(max_length=128)),
                ('magazzino_lettera', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mezzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mezzo_nome', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia_nome', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_nome', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField(default=0.0)),
                ('conto_contabile', models.CharField(default='-', max_length=25)),
                ('voce_spesa', models.CharField(max_length=10)),
                ('centro_costo', models.CharField(max_length=10)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.fornitore')),
                ('magazzino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.magazzino')),
                ('mezzo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.mezzo')),
                ('tipologia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.tipologia')),
                ('arrivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivo', to='mainapp.zona')),
                ('partenza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partenza', to='mainapp.zona')),
            ],
        ),
    ]
