# Generated by Django 5.0.6 on 2024-08-08 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_magazzino_societa_magazzino_societa'),
    ]

    operations = [
        migrations.AddField(
            model_name='listino',
            name='data_ultimo_aggiornamento',
            field=models.DateField(default=datetime.date(1997, 12, 23)),
        ),
    ]
