# Generated by Django 5.0.6 on 2024-08-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_listino_data_ultimo_aggiornamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='listino',
            name='data_upload',
            field=models.DateField(blank=True, null=True),
        ),
    ]
