# Generated by Django 5.0.6 on 2024-08-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_listino_data_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listino',
            name='data_upload',
            field=models.DateField(auto_now_add=True),
        ),
    ]
