# Generated by Django 5.0.6 on 2024-08-12 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_listino_data_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fattura_numero', models.IntegerField()),
                ('fattura_data', models.DateField()),
                ('fattura_documento', models.FileField(upload_to='documenti/')),
                ('fattura_fornitore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.fornitore')),
                ('fattura_utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrefatturaRighe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField()),
                ('prefattura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.prefattura')),
                ('riga_listino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.listino')),
            ],
        ),
        migrations.DeleteModel(
            name='Fattura',
        ),
    ]
