# Generated by Django 5.0.6 on 2024-08-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_prefattura_prefatturarighe_delete_fattura'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefattura',
            name='data_modifica',
            field=models.DateField(auto_now=True),
        ),
    ]
