# Generated by Django 5.0.6 on 2024-08-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_prefattura_finito'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefattura',
            name='societa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.societa'),
            preserve_default=False,
        ),
    ]
