# Generated by Django 5.0.6 on 2024-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseDiTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=128, null=True)),
                ('eta', models.IntegerField(default=0)),
                ('stato', models.CharField(max_length=128)),
            ],
        ),
    ]
